name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: 22.11.0
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4 # v4
      with:
        version: 8
        run_install: true

    - name: Release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm publish